CREATE TABLE IF NOT EXISTS `buyers` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `buyer_name` varchar(255) DEFAULT NULL,
  `buyerdeliveryzone` varchar(128) DEFAULT NULL,
  `buyerdeliverycity` varchar(128) DEFAULT NULL,
  `shipping_address` text,
  `phone` varchar(40) DEFAULT NULL,
  `mobile1` varchar(40) DEFAULT NULL,
  `mobile2` varchar(40) DEFAULT NULL,
  `recipient_name` varchar(255) DEFAULT NULL,
  `shipping_zip` varchar(40) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `delivery_id` varchar(40) NOT NULL,
  `delivery_cost` varchar(128) DEFAULT '0',
  `cod_cost` varchar(40) DEFAULT '0',
  `delivery_type` varchar(40) NOT NULL DEFAULT 'COD',
  `currency` varchar(8) DEFAULT NULL,
  `total_price` varchar(128) DEFAULT NULL,
  `chargeable_amount` varchar(128) DEFAULT NULL,
  `delivery_bearer` varchar(15) NOT NULL,
  `cod_bearer` varchar(15) NOT NULL,
  `cod_method` varchar(15) DEFAULT NULL,
  `ccod_method` varchar(15) DEFAULT NULL,
  `application_id` bigint(20) DEFAULT NULL,
  `application_key` varchar(128) DEFAULT NULL,
  `buyer_id` bigint(20) DEFAULT NULL,
  `merchant_id` bigint(20) DEFAULT NULL,
  `merchant_trans_id` varchar(128) DEFAULT NULL,
  `courier_id` bigint(20) NOT NULL,
  `device_id` bigint(11) NOT NULL,
  `directions` varchar(255) DEFAULT NULL,
  `dir_lat` decimal(18,12) DEFAULT NULL,
  `dir_lon` decimal(18,12) DEFAULT NULL,
  `delivery_note` text,
  `latitude` decimal(18,12) DEFAULT NULL,
  `longitude` decimal(18,12) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 ;
